### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by ruxi** [saeyslab/moduledetection-evaluation#2]
The the source data link from the readme working for anyone else?

 http://bioit.irc.ugent.be/suppl-data/2016/saelens-module-evaluation.zip

**Comment by zouter** [comment]
This is an old link, sorry about that. The data can be downloaded from zenodo [https://zenodo.org/record/1157938](https://zenodo.org/record/1157938)

**Comment by zouter** [comment]
Fixed with a8e941d

**Comment by zouter** [comment]
Thank you!
