### ISSUE TITLE
Code for random baselines

### ISSUE THREAD

**Issue by paidi** [saeyslab/moduledetection-evaluation#5]
I can't find code to compute the random baselines that were used in the paper. Is this included in the repo?

**Comment by miltondp** [comment]
Hi, I'm also trying to find this code. Thank you!

**Comment by miltondp** [comment]
@paidi , could you contact the authors to fix this problem? I see that others are having the same issue [here](https://github.com/saeyslab/moduledetection-evaluation/issues/6).

**Comment by zouter** [comment]
Fixed in #6 , sorry for the delays.
