### ISSUE TITLE
What is the simdistfolder?

### ISSUE THREAD

**Issue by lara-marinelli** [saeyslab/moduledetection-evaluation#8]
Hello
I couldn't find the required structure and content of the simdistfolder mentioned in **moduledetection.py**:

modules = locals()[method["params"]["method"]](E, simdistfolder=dataset["simdistfolder"],  **method["params"])

**Comment by zouter** [comment]
Sorry for the late reply. This was left over from old code but is now no longer required. I updated the code and this error should be resolved now.
